INSERT INTO page_content (project_id, section_id, draft_text, published_text) VALUES
('majdamartinska', 'home.hero.label', 'RODINNÉ · SVATEBNÍ · NEWBORN FOCENÍ', 'RODINNÉ · SVATEBNÍ · NEWBORN FOCENÍ'),
('majdamartinska', 'home.hero.line1', 'Vaše', 'Vaše'),
('majdamartinska', 'home.hero.line2', 'příběhy', 'příběhy'),
('majdamartinska', 'home.hero.line3', 'zachycené navždy', 'zachycené navždy'),
('majdamartinska', 'home.promise.label', 'SLIBUJI VÁM', 'SLIBUJI VÁM'),
('majdamartinska', 'home.promise.title', 'Že focení bude přirozené & v pohodě', 'Že focení bude přirozené & v pohodě'),
('majdamartinska', 'home.promise.text', 'Hledáte fotografku a zároveň pohodářku? Chcete si focení užít a neprotrpět? Jste na správném místě. Dobrá nálada, otevřenost, přirozenost a žádná křeč — to je to, na čem mi při focení záleží.', 'Hledáte fotografku a zároveň pohodářku? Chcete si focení užít a neprotrpět? Jste na správném místě. Dobrá nálada, otevřenost, přirozenost a žádná křeč — to je to, na čem mi při focení záleží.'),
('majdamartinska', 'home.services.label', 'MOJE SLUŽBY', 'MOJE SLUŽBY'),
('majdamartinska', 'home.services.title', 'Moje <em>práce</em>', 'Moje <em>práce</em>'),
('majdamartinska', 'home.service1.name', 'Rodinné a portrétní', 'Rodinné a portrétní'),
('majdamartinska', 'home.service2.name', 'Newborn — miminka', 'Newborn — miminka'),
('majdamartinska', 'home.service3.name', 'Svatby', 'Svatby'),
('majdamartinska', 'home.about.label', 'KDO STOJÍ ZA OBJEKTIVEM?', 'KDO STOJÍ ZA OBJEKTIVEM?'),
('majdamartinska', 'home.about.title', 'Ahoj,<br />jsem <em>Majda</em>', 'Ahoj,<br />jsem <em>Majda</em>'),
('majdamartinska', 'home.about.text', 'Focení mě lákalo od dětství. Mám ráda humor a to se objevuje i v mých fotografiích. Dobrá nálada, otevřenost, přirozenost a žádná křeč — to je to, na čem mi záleží. Taky jsem dost upovídaná, takže kdo se bojí trapného ticha, nebude :)', 'Focení mě lákalo od dětství. Mám ráda humor a to se objevuje i v mých fotografiích. Dobrá nálada, otevřenost, přirozenost a žádná křeč — to je to, na čem mi záleží. Taky jsem dost upovídaná, takže kdo se bojí trapného ticha, nebude :)'),
('majdamartinska', 'home.more1.title', 'Psí kamarádi', 'Psí kamarádi'),
('majdamartinska', 'home.more1.text', 'Máš doma mazlíka? Chceš ho mít na fotkách? Tož to tady jsi správně.', 'Máš doma mazlíka? Chceš ho mít na fotkách? Tož to tady jsi správně.'),
('majdamartinska', 'home.more2.title', 'Těhotenské focení', 'Těhotenské focení'),
('majdamartinska', 'home.more2.text', 'Krásné období, které si zaslouží zachytit na fotografiích.', 'Krásné období, které si zaslouží zachytit na fotografiích.'),
('majdamartinska', 'home.more3.title', 'Portréty', 'Portréty'),
('majdamartinska', 'home.more3.text', 'Profesionální portrétní fotografie pro vaši prezentaci i osobní účely.', 'Profesionální portrétní fotografie pro vaši prezentaci i osobní účely.'),
('majdamartinska', 'home.testimonials.label', 'MILÁ SLOVA', 'MILÁ SLOVA'),
('majdamartinska', 'home.testimonial.text', '„Spolupracovat s Majdou byla naprostá paráda. S naším 14denním synem zacházela více než mateřsky. Fotografie jsou plné něhy, lásky a profesionality."', '„Spolupracovat s Majdou byla naprostá paráda. S naším 14denním synem zacházela více než mateřsky. Fotografie jsou plné něhy, lásky a profesionality."'),
('majdamartinska', 'home.testimonial.name', 'Bára M.', 'Bára M.'),
('majdamartinska', 'home.testimonial.type', 'Newborn focení', 'Newborn focení'),
('majdamartinska', 'home.studio.label', 'ATELIÉR', 'ATELIÉR'),
('majdamartinska', 'home.studio.title', 'Ateliér <em>Praha Suchdol</em>', 'Ateliér <em>Praha Suchdol</em>'),
('majdamartinska', 'home.studio.text', 'Disponuji velkým a dobře vybaveným ateliérem v klidné části Praha — Suchdol.', 'Disponuji velkým a dobře vybaveným ateliérem v klidné části Praha — Suchdol.'),
('majdamartinska', 'home.cta.label', 'JSME NA PODOBNÉ VLNĚ?', 'JSME NA PODOBNÉ VLNĚ?'),
('majdamartinska', 'home.cta.title', 'Pojďme <em>do toho</em>', 'Pojďme <em>do toho</em>')
ON CONFLICT (project_id, section_id) DO UPDATE SET
  draft_text = EXCLUDED.draft_text,
  published_text = EXCLUDED.published_text,
  updated_at = now();
